### ISSUE TITLE
New Mod Names

### ISSUE THREAD

**Issue by TumeniNodes** [TumeniNodes/aufbauen#3]
Need some ideas for good names, for two new mods.
One, will be where all wood type nodes are kept
The other, where all stone type nodes are kept.

I want default to only be those related to mapgen, and then all other nodes such as brick, block etc to be kept within those two mods.
Any ideas?

**Comment by SmallJoker** [comment]
Wood:  holz_kollektion, holzbau
Stone: stein_kollektion, steinbau

**Comment by TumeniNodes** [comment]
Yes, I think keeping the names that simple works.
I had thought of those names but thought they may be "too simple", thus confusing but, now someone else mentioning them, I think it works fine.

Thanks SmallJoker

**Comment by TumeniNodes** [comment]
https://github.com/TumeniNodes/aufbauen/commit/b221e4c57798c990237460476ef2ff7c73964326
